name = "Jute"
uuid = "82bedeac-9837-5b62-883a-b5b3b7c811c5"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
version = "0.2.2"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArgParse = "≥ 0.6.0"
DataStructures = "≥ 0.12.0"
julia = "≥ 1.0.0"
